### ISSUE TITLE
gatsby-theme-notes 2.0.1 appears broken

### ISSUE THREAD

**Issue by jaytula** [gatsbyjs/themes#59]
The instructions here https://www.gatsbyjs.org/packages/gatsby-theme-notes/ in the *Manually add to your site* section does not work because it install the newer `2.0.1` version.  Switching to the older `1.3.x` works.

```shell
# This leads to a working site
gatsby new my-themed-notes https://github.com/gatsbyjs/gatsby-starter-notes-theme
cd my-theme-notes
npm run develop

# Check that it is working at  http://localhost:8000 . Ctrl-C to stop server after checking

# Update to the latest 2.0.1
npm i gatsby-theme-notes@latest
npm run develop

# A multitude of errors when checking http://localhost:8000
```

![image](https://user-images.githubusercontent.com/75389/89832678-87a83c80-db14-11ea-83a9-46cc171d73ec.png)

It appears there's been some major changes from version 1.x  to version 2+

**Comment by gillkyle** [comment]
I'm unable to replicate the exact issue:

```
TypeError: Object(...) is not a function
```
that seems to be coming from `gatsby-plugin-theme-ui`, though this issue did help me uncover a similar, related issue. I saw an issue in theme-ui when installing `gatsby-theme-notes` in a fresh project (like mentioned in the original issue), but got an error hinting that components weren't being exported correctly.

Digging into it, a handful of theme-ui components used in the layout component of the theme are no longer exported by theme-ui (and no longer going to be provided by theme-ui) [from version ^0.3](https://github.com/system-ui/theme-ui/blob/master/CHANGELOG.md#v030-2020-01-22):
https://github.com/gatsbyjs/themes/blob/32525ddbaeb1d9368b72370ce9ebf774a41081bb/packages/gatsby-theme-notes/src/components/layout.js#L4

I suspect these issues could both be resolved by fixing the problem components. I imagine the original issue here was a result of moving theme-ui package versions since the issue was created.
